package Questions.Notification_System.NotificationChannelClient.Impl;

import Questions.Notification_System.NotificationChannelClient.FacebookChannelClient;

public class FacebookChannelClientImpl implements FacebookChannelClient {
}
