package Questions.Notification_System.NotificationChannelClient.Impl;

import Questions.Notification_System.NotificationChannelClient.InstagramChannelClient;

public class InstagramChannelClientImpl implements InstagramChannelClient {
}
