package Questions.Notification_System.NotificationChannelClient.Impl;

import Questions.Notification_System.NotificationChannelClient.MobilePushChannelClient;

public class MobilePushChannelClientImpl implements MobilePushChannelClient {
}
