package Questions.Notification_System.NotificationChannelClient.Impl;

import Questions.Notification_System.NotificationChannelClient.WebPushChannelClient;

public class WebPushChannelClientImpl implements WebPushChannelClient {
}
