package Questions.Notification_System.NotificationChannelClient.Impl;

import Questions.Notification_System.NotificationChannelClient.WhatsappChannelClient;

public class WhatsappChannelClientImpl implements WhatsappChannelClient {
}
